# Generated by Django 4.0.5 on 2022-07-20 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cim_service', '0004_alter_company_parent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cim_service.company'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('Rx', 'Приёмник'), ('Tx', 'Передатчик'), ('Load_shedding', 'САОН'), ('Frequency_load_shedding', 'АЧР'), ('Stability_control_automatic', 'АПНУ'), ('Over_power_automatic', 'АОПО')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('unit_id', 'company_id', 'type')},
        ),
    ]
