# Generated by Django 4.0.5 on 2022-08-16 18:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cim_service', '0005_alter_company_parent_company_alter_device_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Feeder', 'Фидер'), ('Generator', 'Генератор'), ('BusSectionConnector', 'ШСВ'), ('ReactivePowerCompensator', 'Компенсатор реактивной мощности'), ('PowerTransformer', 'Силовой трансформатор'), ('Line', 'ЛЭП')], max_length=50)),
            ],
            options={
                'verbose_name': 'Первичное оборудование',
                'verbose_name_plural': 'Первичное оборудование',
            },
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('category', models.IntegerField(choices=[(1, '1 категория'), (2, '2 категория'), (3, '3 категория')])),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cim_service.equipment')),
            ],
            options={
                'verbose_name': 'Фидер',
                'verbose_name_plural': 'Фидеры',
            },
            bases=('cim_service.equipment',),
        ),
        migrations.CreateModel(
            name='Switchgear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('base_voltage', models.IntegerField(choices=[(6, '6 кВ'), (10, '10 кВ'), (35, '35 кВ'), (110, '110 кВ'), (220, '220 кВ'), (330, '330 кВ'), (500, '500 кВ'), (750, '750 кВ'), (1150, '1150 кВ')])),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cim_service.substation')),
            ],
            options={
                'verbose_name': 'Распредустройство',
                'verbose_name_plural': 'Распредустройства',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='switchgear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cim_service.switchgear'),
        ),
    ]
