# Generated by Django 4.0.5 on 2022-07-06 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beam',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1cf5b84e-b3a0-4930-aa64-866b78691499'), editable=False, primary_key=True, serialize=False)),
                ('in_service', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Пучок',
                'verbose_name_plural': 'Пучки',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('35ed8a53-4e56-4612-95f5-807fc721129c'), editable=False, primary_key=True, serialize=False)),
                ('in_service', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ветвь',
                'verbose_name_plural': 'Ветви',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('68c0b853-c68c-4bb7-92ae-e992a0a899a2'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('local_number', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Узел',
                'verbose_name_plural': 'Узлы',
            },
        ),
        migrations.CreateModel(
            name='Node_Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d8028b0b-b5ea-401e-9cca-f4f75f460cc4'), editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('input', 'Вход'), ('output', 'Выход')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5119b0c0-1793-49cf-bfe3-b93079cc0442'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('in_service', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Положение переключателя',
                'verbose_name_plural': 'Положения переключателей',
            },
        ),
        migrations.CreateModel(
            name='Position_Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('17d91e07-bee6-465a-8faa-7b4150d470ac'), editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('on', 'Вкл'), ('off', 'Откл')], default='off', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e3a445c0-a049-41c3-aea8-520f1c9e8908'), editable=False, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Переключатель',
                'verbose_name_plural': 'Переключатели',
            },
        ),
    ]
