# Generated by Django 4.0.5 on 2022-07-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cim_service', '0001_initial'),
        ('channels_and_devices_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cim_service.device'),
        ),
        migrations.AddField(
            model_name='position_branch',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels_and_devices_service.branch'),
        ),
        migrations.AddField(
            model_name='position_branch',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels_and_devices_service.position'),
        ),
        migrations.AddField(
            model_name='position',
            name='selector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='channels_and_devices_service.selector'),
        ),
        migrations.AddField(
            model_name='node_branch',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels_and_devices_service.branch'),
        ),
        migrations.AddField(
            model_name='node_branch',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels_and_devices_service.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='branches',
            field=models.ManyToManyField(through='channels_and_devices_service.Node_Branch', to='channels_and_devices_service.branch'),
        ),
        migrations.AddField(
            model_name='node',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cim_service.device'),
        ),
        migrations.AddField(
            model_name='branch',
            name='beam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='channels_and_devices_service.beam'),
        ),
    ]
