# Generated by Django 4.0.5 on 2022-07-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_and_devices_service', '0003_alter_beam_id_alter_branch_id_alter_node_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='local_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
