# Generated by Django 4.0.5 on 2022-07-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_and_devices_service', '0004_alter_node_local_number_alter_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_branch',
            name='type',
            field=models.CharField(choices=[('direct', 'Прямо'), ('reverse', 'Обратно')], max_length=10),
        ),
    ]
